name: bot
description: A joke discord bot.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  nyxx: ^6.5.2
  dotenv: ^4.2.0
  nyxx_commands: ^6.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
